# Generated by Django 3.1.4 on 2020-12-18 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oauth2', '0003_accesstoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access_token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_token', to='oauth2.accesstoken')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauth2.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oauth2_refreshtoken', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'refreshToken',
                'verbose_name_plural': 'refreshTokens',
            },
        ),
    ]
