# Generated by Django 3.1.7 on 2021-03-19 11:25

from django.db import migrations, models
import yesboss.storing.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_type', models.SmallIntegerField()),
                ('file_path', models.FileField(max_length=300, upload_to=yesboss.storing.models.get_file_folder)),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
