# Generated by Django 3.1.7 on 2021-03-04 20:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import yesboss.base.fields
import yesboss.base.phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=yesboss.base.fields.lang_dict_field)),
                ('alias', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.JSONField(default=yesboss.base.fields.lang_dict_field)),
                ('alias', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('phone_number', yesboss.base.phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=30, null=True, unique=True)),
                ('nickname', models.CharField(max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=70, null=True)),
                ('last_name', models.CharField(blank=True, max_length=70)),
                ('user_type', models.SmallIntegerField(default=1)),
                ('tab_number', models.IntegerField()),
                ('tg_id', models.BigIntegerField(blank=True, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('lang', models.SmallIntegerField(default=1)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('limit_credit', models.IntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='user.statuses')),
                ('types', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_types', to='user.types')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ['-date_joined'],
                'get_latest_by': 'date_joined',
            },
        ),
    ]
