# Generated by Django 3.1.7 on 2021-03-04 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yesboss.base.phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', yesboss.base.phonenumber_field.modelfields.PhoneNumberField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-created_dt'],
                'get_latest_by': 'created_dt',
            },
        ),
    ]
