# Generated by Django 3.1.7 on 2021-03-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_terms',
            field=models.BooleanField(default=False),
        ),
    ]
