# Generated by Django 3.1.7 on 2021-03-04 20:16

from django.db import migrations, models
import django.db.models.deletion
import yesboss.base.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(db_index=True, editable=False, null=True)),
                ('name', models.JSONField(default=yesboss.base.fields.lang_dict_field)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categorypostion', to='hr.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
