# Generated by Django 3.1.7 on 2021-03-04 20:16

from django.db import migrations, models
import yesboss.base.fields
import yesboss.hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_positions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=yesboss.hr.models.default_schdule_data)),
                ('name', models.JSONField(blank=True, default=yesboss.base.fields.lang_dict_field, null=True)),
                ('alias', models.CharField(max_length=32, unique=True)),
                ('is_active', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
    ]
