# Generated by Django 3.1.7 on 2021-03-04 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import yesboss.hr.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_contacts'),
        ('geo', '0003_district'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0006_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('salary', models.JSONField(blank=True, default=yesboss.hr.models.default_salary)),
                ('languages', models.JSONField(blank=True, null=True)),
                ('about', models.CharField(blank=True, max_length=600)),
                ('views_count', models.IntegerField(default=0, editable=False)),
                ('contact_count', models.IntegerField(default=0, editable=False)),
                ('postion', models.CharField(blank=True, max_length=600, null=True)),
                ('file_type', models.SmallIntegerField(blank=True, null=True)),
                ('file_path', models.FileField(blank=True, max_length=300, null=True, upload_to=yesboss.hr.models.get_file_folder)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.SmallIntegerField(blank=True, null=True)),
                ('skills', models.CharField(blank=True, max_length=600, null=True)),
                ('created_dt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_dt', models.DateTimeField(auto_now=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_contacts', to='user.contacts')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_resume', to='geo.district')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_experience', to='hr.experience')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region_resume', to='geo.region')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules_resume', to='hr.schedules')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_resume', to='hr.statuses')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_resumes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
