# Generated by Django 3.1.7 on 2021-03-04 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_categories', to='hr.category')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_categories_m', to='hr.resume')),
            ],
            options={
                'unique_together': {('resume', 'category')},
            },
        ),
    ]
