# Generated by Django 3.1.7 on 2021-03-05 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0010_vacancicategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacanciLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies_language', to='hr.languages')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies_language_v', to='hr.vacancies')),
            ],
            options={
                'unique_together': {('vacancy', 'language')},
            },
        ),
    ]
