# Generated by Django 3.1.7 on 2021-03-05 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0011_vacancilanguage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancies',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vacancies',
            name='subcats',
        ),
    ]
