# Generated by Django 3.1.7 on 2021-03-05 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0012_auto_20210305_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancies',
            name='position_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
