# Generated by Django 3.1.7 on 2021-03-21 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storing', '0002_auto_20210321_2005'),
        ('hr', '0014_auto_20210305_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='files',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vavancies_files', to='storing.files'),
        ),
    ]
