# Generated by Django 3.1.7 on 2021-03-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0017_auto_20210323_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
