# Generated by Django 3.1.7 on 2021-03-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0018_resume_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file_path',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='file_type',
        ),
    ]
