# Generated by Django 3.1.7 on 2021-03-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0021_resume_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='postion',
        ),
        migrations.AddField(
            model_name='resume',
            name='position_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
