# Generated by Django 3.1.7 on 2021-03-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('messages', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
