# Generated by Django 3.1.7 on 2021-04-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg', '0002_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=400)),
                ('vacancy_channel_link', models.CharField(max_length=200)),
                ('vacancy_channel_id', models.CharField(max_length=200)),
                ('resume_channel_link', models.CharField(max_length=400)),
                ('resume_channel_id', models.CharField(max_length=400)),
            ],
        ),
    ]
